image_speed = 1;
launched = false;
scr_Screen_Shake(7,15, false);
audio_play_sound(snd_explosion,0,false);
destroy_on_impact = true;
attach_to_player = 0;
boss_projectile=false;
mask_index = sprite_index;
vspd = 0;
hspd = 0;
init_damage = damage;
init_sprite = sprite_index;